accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('registro/', views.registrar, name='registro'),
    path('visualizar/', views.visualizar_clientes, name='visualizar_clientes'),
    path('pesquisar/', views.pesquisar_clientes, name='pesquisar_clientes'),
    path('editar_cliente/<int:pk>/', views.editar_cliente, name='editar_cliente'),
    path('adicionar_interacao/<int:cliente_id>/', views.adicionar_interacao, name='adicionar_interacao'),
    path('historico_interacoes/<int:cliente_id>/', views.historico_interacoes, name='historico_interacoes'),
    path('perfil/<int:cliente_id>/', views.visualizar_perfil, name='visualizar_perfil'),
    path('compras_e_preferencias/<int:cliente_id>/', views.lista_compras_e_preferencias, name='lista_compras_e_preferencias'),
    path('adicionar_compra/<int:cliente_id>/', views.adicionar_compra, name='adicionar_compra'),
    path('adicionar_preferencia/<int:cliente_id>/', views.adicionar_preferencia, name='adicionar_preferencia'),
]

jacto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('opportunity/', include('opportunity.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class UserProfile(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField()
    telefone = models.CharField(max_length=20)
    data_nascimento = models.DateField()
    cpf_cnpj = models.CharField(max_length=20)
    numero = models.CharField(max_length=10)
    cidade = models.CharField(max_length=100)
    cep = models.CharField(max_length=9)
    rua = models.CharField(max_length=255)
    
    def __str__(self):
        return self.nome

class Interaction(models.Model):
    OP_CHOICES = (
        ('Reunião', 'Reunião'),
        ('Email', 'Email'),
        ('Chamada', 'Chamada'),
        ('Chat', 'Chat'),
    )
    id_cliente = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    data = models.DateField(default=timezone.now)
    choice = models.CharField(max_length=10, choices=OP_CHOICES)
    descricao = models.CharField(max_length=200)

    def __str__(self):
        return f"Interacao {self.id} - Cliente: {self.id_cliente}, Tipo: {self.choice}, Data: {self.data}"

class Compra(models.Model):
    id_cliente = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    data = models.DateField(default=timezone.now)  # Define a data automaticamente
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    produtos = models.CharField(max_length=200)

    def __str__(self):
        return f"Compra {self.id} - Cliente: {self.id_cliente}, Data: {self.data}"
    

class Preferencia(models.Model):
    id_cliente = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    preferencia = models.CharField(max_length=200)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nome', 'email', 'telefone', 'data_nascimento', 'cpf_cnpj', 'numero', 'cidade', 'cep', 'rua']
        
class ClienteSearchForm(forms.Form):
    nome = forms.CharField(label='Nome', required=False)
    cpf_cnpj = forms.CharField(label='CPF/CNPJ', required=False)

class InteractionForm(forms.ModelForm):
    class Meta:
        model = Interaction
        fields = ['choice', 'descricao']

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['valor', 'produtos']

class PreferenciaForm(forms.ModelForm):
    class Meta:
        model = Preferencia
        fields = ['preferencia']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from .models import *

def registrar(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('visualizar_clientes')
    else:
        form = UserProfileForm()
    return render(request, 'accounts/registro.html', {'form': form})



def visualizar_clientes(request):
    # Recupera todos os perfis de usuário
    perfis = UserProfile.objects.all()
    return render(request, 'clientes/visualizar_clientes.html', {'perfis': perfis})

def visualizar_perfil(request, cliente_id):
    cliente = get_object_or_404(UserProfile, pk=cliente_id)
    return render(request, 'clientes/visualizar_perfil.html', {'cliente': cliente})

def pesquisar_clientes(request):
    if request.method == 'POST':
        form = ClienteSearchForm(request.POST)
        if form.is_valid():
            nome = form.cleaned_data['nome']
            cpf_cnpj = form.cleaned_data['cpf_cnpj']
            clientes = UserProfile.objects.filter(nome__icontains=nome, cpf_cnpj__icontains=cpf_cnpj)
            return render(request, 'clientes/resultado_pesquisa.html', {'clientes': clientes})
    else:
        form = ClienteSearchForm()
    return render(request, 'clientes/pesquisar_clientes.html', {'form': form})

def editar_cliente(request, pk):
    cliente = get_object_or_404(UserProfile, pk=pk)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('visualizar_clientes')
    else:
        form = UserProfileForm(instance=cliente)
    return render(request, 'clientes/editar_cliente.html', {'form': form})

def historico_interacoes(request, cliente_id):
    cliente = UserProfile.objects.get(pk=cliente_id)
    interacoes = Interaction.objects.filter(id_cliente=cliente)
    return render(request, 'clientes/historico_interacoes.html', {'cliente': cliente, 'interacoes': interacoes})

def adicionar_interacao(request, cliente_id):
    cliente = UserProfile.objects.get(pk=cliente_id)
    if request.method == 'POST':
        form = InteractionForm(request.POST)
        if form.is_valid():
            interacao = form.save(commit=False)
            interacao.id_cliente = cliente
            interacao.save()
            return redirect('historico_interacoes', cliente_id=cliente.id)
    else:
        form = InteractionForm()
    return render(request, 'clientes/adicionar_interacao.html', {'form': form, 'cliente': cliente})

def lista_compras_e_preferencias(request, cliente_id):
    cliente = UserProfile.objects.get(pk=cliente_id)
    compras = cliente.compra_set.all()
    preferencias = cliente.preferencia_set.all()
    return render(request, 'compras/compras_preferencias.html', {'cliente': cliente, 'compras': compras, 'preferencias': preferencias})

def adicionar_compra(request, cliente_id):
    cliente = UserProfile.objects.get(pk=cliente_id)
    if request.method == 'POST':
        form = CompraForm(request.POST)
        if form.is_valid():
            compra = form.save(commit=False)
            compra.id_cliente = cliente
            compra.save()
            return redirect('lista_compras_e_preferencias', cliente_id=cliente.id)
    else:
        form = CompraForm()
    return render(request, 'compras/adicionar_compra.html', {'form': form})



def adicionar_preferencia(request, cliente_id):
    cliente = UserProfile.objects.get(pk=cliente_id)
    if request.method == 'POST':
        form = PreferenciaForm(request.POST)
        if form.is_valid():
            preferencia = form.save(commit=False)
            preferencia.id_cliente = cliente
            preferencia.save()
            return redirect('lista_compras_e_preferencias', cliente_id=cliente.id)
    else:
        form = PreferenciaForm()
    return render(request, 'compras/adicionar_preferencia.html', {'form': form})

accounts/templates/compras/adicionar_compra.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Compra</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="form-container">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <img src="{% static 'images/jacto.png' %}" alt="Jacto" class="jacto-logo">
        <h1>Adicionar compra</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group">
                    <label for="id_valor">Valor:</label>
                    {{ form.valor }}
                </div>
                <div class="form-group">
                    <label for="id_produto">Produto:</label>
                    {{ form.produtos }}
                </div>
            </div>
            <button type="submit" class="btn-submit">Adicionar</button>
        </form>
    </div>
</body>
</html>

accounts/templates/compras/adicionar_preferencia.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Preferências</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="form-container">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <img src="{% static 'images/jacto.png' %}" alt="Jacto" class="jacto-logo">
        <h1>Adicionar preferência</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group">
                    <label for="id_preferencia">Preferencia:</label>
                    {{ form.preferencia }}
                </div>
            </div>
            <button type="submit" class="btn-submit">Adicionar</button>
        </form>
    </div>
</body>
</html>

accounts/templates/compras/compras_preferencias.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compras e Preferências</title>
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
</head>
<body>
    <header class="shortcut-bar">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <nav>
            <a href="{% url 'opportunity_management'%}">Gerenciar vendas</a>
            <a href="{% url 'pesquisar_clientes'%}">Pesquisar cliente</a>
            <a href="{% url 'visualizar_clientes'%}">Visualizar cliente</a>
            <a href="{% url 'criar_proposta'%}">Criar propostas</a>
            <button class="btn-back" onclick="history.back()">Voltar</button>
        </nav>
    </header>
    <main class="main-content">
        <div class="container">
            <div class="header">
                <img src="{% static 'images/logo.png' %}" alt="Jacto">
                <h1>Compras e Preferências de {{ cliente.nome }}</h1>
            </div>

            <div class="section">
                <div class="section-title">Compras:</div>
                <div class="items">
                    {% for compra in compras %}
                    <div class="item">
                        <h3>Valor: {{ compra.valor }}</h3>
                        <p>Produto: {{ compra.produto }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="section">
                <div class="section-title">Preferências:</div>
                <div class="items">
                    {% for preferencia in preferencias %}
                    <div class="item">
                        <p>Preferência: {{ preferencia.preferencia }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
</body>
</html>