jacto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('opportunity/', include('opportunity.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

opportunity/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('oportunidades/', views.opportunity_management, name='opportunity_management'),
    path('oportunidades/update_opportunity_stage/', views.update_opportunity_stage, name='update_opportunity_stage'),
    path('criar/', views.create_proposal, name='criar_proposta'),
    path('listar/', views.listar_propostas, name='listar_propostas'),
    path('detalhes/<int:proposal_id>/', views.detail_proposal, name='detalhes_proposta'),
    path('excluir/<int:proposal_id>/', views.excluir_proposta, name='excluir_proposta'),
    path('enviar_email/<int:proposal_id>/', views.enviar_proposta_por_email, name='enviar_proposta_por_email'),
]

opportunity/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import UserProfile

class Opportunity(models.Model):
    STAGE_CHOICES = [
        ('prospeccao', 'Prospecção'),
        ('negociacao', 'Negociação'),
        ('fechamento', 'Fechamento'),
        ('ganho', 'Ganho'),
        ('perdido', 'Perdido'),
    ]

    cliente = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    etapa = models.CharField(max_length=20, choices=STAGE_CHOICES)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    data_criacao = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"Oportunidade para {self.cliente} - Etapa: {self.etapa}"

class Proposal(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.CharField(max_length=100)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    prazo_validade = models.DateField()
    itens = models.CharField(max_length=100)
    termos_condicoes = models.CharField(max_length=100)

    def __str__(self):
        return self.titulo

opportunity/forms.py
from django import forms
from .models import *

class OpportunityForm(forms.ModelForm):
    cliente = forms.ModelChoiceField(queryset=UserProfile.objects.all(), label='Cliente')  

    class Meta:
        model = Opportunity
        fields = ['cliente', 'etapa', 'valor']

class ProposalForm(forms.ModelForm):
    class Meta:
        model = Proposal
        fields = ['titulo', 'descricao', 'preco', 'prazo_validade', 'itens', 'termos_condicoes']

opportunity/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail
from django.template.loader import render_to_string
from .forms import *
from .models import *
import json


def opportunity_management(request):
    if request.method == 'POST':
        form = OpportunityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('opportunity_management')
    else:
        form = OpportunityForm()
    
    opportunities = Opportunity.objects.all()
    prospects = opportunities.filter(etapa='prospeccao')
    negotiations = opportunities.filter(etapa='negociacao')
    closures = opportunities.filter(etapa='fechamento')
    wins = opportunities.filter(etapa='ganho')
    losses = opportunities.filter(etapa='perdido')
    
    return render(request, 'sales_cycle_tracking/opportunity_management.html', {
        'form': form,
        'prospects': prospects,
        'negotiations': negotiations,
        'closures': closures,
        'wins': wins,
        'losses': losses,
    })

@csrf_exempt
def update_opportunity_stage(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        opportunity_id = data.get('opportunity_id')
        new_stage = data.get('new_stage')
        
        try:
            opportunity = Opportunity.objects.get(pk=opportunity_id)
            opportunity.etapa = new_stage
            opportunity.save()
            return JsonResponse({'success': True})
        except Opportunity.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Oportunidade não encontrada'})
    
    return JsonResponse({'success': False, 'error': 'Método não permitido'})

def create_proposal(request):
    if request.method == 'POST':
        form = ProposalForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_propostas')  # Corrigido para 'listar_propostas'
    else:
        form = ProposalForm()
    return render(request, 'sales_cycle_tracking/proposal.html', {'form': form})

def listar_propostas(request):
    propostas = Proposal.objects.all()
    return render(request, 'sales_cycle_tracking/list_proposal.html', {'propostas': propostas})

def detail_proposal(request, proposal_id):
    proposta = get_object_or_404(Proposal, pk=proposal_id)
    return render(request, 'sales_cycle_tracking/detail_proposal.html', {'proposta': proposta})

def excluir_proposta(request, proposal_id):
    proposta = get_object_or_404(Proposal, pk=proposal_id)
    if request.method == 'POST':
        proposta.delete()
        return redirect('listar_propostas')
    return render(request, 'sales_cycle_tracking/excluir_proposta.html', {'proposta': proposta})

from django.core.mail import send_mail
from django.template.loader import render_to_string

def enviar_proposta_por_email(request, proposal_id):
    proposta = get_object_or_404(Proposal, pk=proposal_id)
    # Lógica para obter os e-mails dos destinatários (suponha que estejam em um campo no modelo UserProfile)
    destinatarios = UserProfile.objects.values_list('email', flat=True)
    # Renderizar o conteúdo do e-mail a partir de um template
    email_content = render_to_string('sales_cycle_tracking/email_proposta.html', {'proposta': proposta})
    # Enviar e-mail para todos os destinatários
    send_mail(
        'Nova Proposta Disponível',
        email_content,
        '******@exemple.com',
        destinatarios,
        fail_silently=False,
    )
    return redirect('listar_propostas')

opportunity/templates/sales_cycle_tracking/detail_proposal.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes da Proposta</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="shortcut-bar">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <nav>
            <a href="{% url 'registro'%}">Registro cliente</a>
            <a href="{% url 'opportunity_management'%}">Gerenciar vendas</a>
            <a href="{% url 'visualizar_clientes'%}">Visualizar cliente</a>
            <a href="{% url 'criar_proposta'%}">Criar propostas</a>
            <button class="btn-back" onclick="history.back()">Voltar</button>
        </nav>
    </header>

    <main class="main-content">
        <div class="form-container">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
            <h3>Detalhe proposta</h3>
            <h2>{{ proposta.titulo }}</h2>
            <div class="proposal-details">
                <div class="form-row">
                    <div class="form-group">
                        <label for="id_descricao">Descrição</label>
                        <p>{{ proposta.descricao }}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_preco">Preço</label>
                        <p>{{ proposta.preco }}</p>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="id_prazo">Prazo de validade</label>
                        <p>{{ proposta.prazo_validade }}</p>
                    </div>
                    <div class="form-group">
                        <label for="id_itens">Itens</label>
                        <p>{{ proposta.itens }}</p>
                    </div>
                </div>
            </div>
        </div>
    </main>
</body>
</html>

opportunity/templates/sales_cycle_tracking/email_proposta.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Nova Proposta</title>
</head>
<body>
    <h1>Nova Proposta Disponível</h1>
    <p>Confira a nova proposta que acabamos de enviar!</p>
    <p>Título: {{ proposta.titulo }}</p>
    <p>Descrição: {{ proposta.descricao }}</p>
    <p>Preço: {{ proposta.preco }}</p>
    <p>Itens: {{ proposta.itens }}</p>

</body>
</html>

opportunity/templates/sales_cycle_tracking/excluir_proposta.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Excluir Proposta</title>
</head>
<body>
    <h1>Excluir Proposta</h1>
    <p>Tem certeza que deseja excluir a proposta "{{ proposta.titulo }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar Exclusão</button>
    </form>
</body>
</html>

opportunity/templates/sales_cycle_tracking/list_proposal.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualizar Propostas</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <header class="shortcut-bar">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <nav>
            <a href="{% url 'registro'%}">Registro cliente</a>
            <a href="{% url 'opportunity_management'%}">Gerenciar vendas</a>
            <a href="{% url 'pesquisar_clientes'%}">Pesquisar cliente</a>
            <a href="{% url 'criar_proposta'%}">Criar propostas</a>
            <button class="btn-back" onclick="history.back()">Voltar</button>
        </nav>
    </header>
    
    <main class="main-content">
        <div class="form-container">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
            <h2>Visualizar propostas</h2>
            <div class="result-container">
                {% for proposta in propostas %}
                <div class="result-card">
                    <h3>Proposta:{{ proposta.titulo }}<br></h3>
                    <div class="buttons">
                        <a href="{% url 'detalhes_proposta' proposta.id %}">Detalhes</a>
                        <form method="post" action="{% url 'excluir_proposta' proposta.id %}" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn-view">Excluir</button>
                        </form>
                        <form method="post" action="{% url 'enviar_proposta_por_email' proposta.id %}" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn-view">Enviar por E-mail</button>
                        </form>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </main>    
</body>
</html>

opportunity/templates/sales_cycle_tracking/opportunity_management.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Gestão de Oportunidades</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

    <div class="shortcut-bar">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <a href="{% url 'registro'%}">Registro cliente</a>
        <a href="{% url 'opportunity_management'%}">Gerenciar vendas</a>
        <a href="{% url 'visualizar_clientes'%}">Visualizar cliente</a>
        <a href="{% url 'listar_propostas'%}">Ver propostas</a>
        <button class="btn-back" onclick="history.back()">Voltar</button>
    </div>

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_cliente">Cliente:</label>
            {{ form.cliente }}
        </div>
        <div class="form-group">
            <label for="id_etapa">Etapa:</label>
            {{ form.etapa }}
        </div>
        <div class="form-group">
            <label for="id_valor">Valor:</label>
            {{ form.valor }}
        </div>
        <button type="submit">Salvar</button>
    </form>
    <div class="stage-container">
        <div id="prospeccao" class="stage" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h2>Prospecção</h2>
            {% for opportunity in prospects %}
            <div class="opportunity" draggable="true" id="opportunity_{{ opportunity.id }}" ondragstart="drag(event)">
                <div class="details">
                    <strong>Nome:</strong> {{ opportunity.cliente.nome }}<br>
                    <strong>CPF/CNPJ:</strong> {{ opportunity.cliente.cpf_cnpj }}<br>
                    <strong>Valor:</strong> {{ opportunity.valor }}<br>
                </div>
                <div class="buttons">
                    <a href="{% url 'adicionar_interacao' opportunity.cliente.id %}">Adicionar <br>interação</a>
                    <a href="{% url 'historico_interacoes' opportunity.cliente.id %}">Histórico <br>interação</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <div id="negociacao" class="stage" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h2>Negociação</h2>
            {% for opportunity in negotiations %}
            <div class="opportunity" draggable="true" id="opportunity_{{ opportunity.id }}" ondragstart="drag(event)">
                <div class="details">
                    <strong>Nome:</strong> {{ opportunity.cliente.nome }}<br>
                    <strong>CPF/CNPJ:</strong> {{ opportunity.cliente.cpf_cnpj }}<br>
                    <strong>Valor:</strong> {{ opportunity.valor }}<br>
                </div>
                <div class="buttons">
                    <a href="{% url 'adicionar_interacao' opportunity.cliente.id %}">Adicionar <br>interação</a>
                    <a href="{% url 'historico_interacoes' opportunity.cliente.id %}">Histórico <br>interação</a><br>
                </div>
            </div>
            {% endfor %}
        </div>
        <div id="fechamento" class="stage" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h2>Fechamento</h2>
            {% for opportunity in closures %}
            <div class="opportunity" draggable="true" id="opportunity_{{ opportunity.id }}" ondragstart="drag(event)">
                <div class="details">
                    <strong>Nome:</strong> {{ opportunity.cliente.nome }}<br>
                    <strong>CPF/CNPJ:</strong> {{ opportunity.cliente.cpf_cnpj }}<br>
                    <strong>Valor:</strong> {{ opportunity.valor }}<br>
                </div>
                <div class="buttons">
                    <a href="{% url 'adicionar_interacao' opportunity.cliente.id %}">Adicionar <br>interação</a>
                    <a href="{% url 'historico_interacoes' opportunity.cliente.id %}">Histórico <br>interação</a><br>
                </div>
            </div>
            {% endfor %}
        </div>
        <div id="ganho" class="stage" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h2>Ganho</h2>
            {% for opportunity in wins %}
            <div class="opportunity" draggable="true" id="opportunity_{{ opportunity.id }}" ondragstart="drag(event)">
                <div class="details">
                    <strong>Nome:</strong> {{ opportunity.cliente.nome }}<br>
                    <strong>CPF/CNPJ:</strong> {{ opportunity.cliente.cpf_cnpj }}<br>
                    <strong>Valor:</strong> {{ opportunity.valor }}<br>
                </div>
                <div class="buttons">
                    <a href="{% url 'adicionar_interacao' opportunity.cliente.id %}">Adicionar <br>interação</a>
                    <a href="{% url 'historico_interacoes' opportunity.cliente.id %}">Histórico <br>interação</a><br>
                </div>
            </div>
            {% endfor %}
        </div>
        <div id="perdido" class="stage" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h2>Perdido</h2>
            {% for opportunity in losses %}
            <div class="opportunity" draggable="true" id="opportunity_{{ opportunity.id }}" ondragstart="drag(event)">
                <div class="details">
                    <strong>Nome:</strong> {{ opportunity.cliente.nome }}<br>
                    <strong>CPF/CNPJ:</strong> {{ opportunity.cliente.cpf_cnpj }}<br>
                    <strong>Valor:</strong> {{ opportunity.valor }}<br>
                </div>
                <div class="buttons">
                    <a href="{% url 'adicionar_interacao' opportunity.cliente.id %}">Adicionar <br>interação</a>
                    <a href="{% url 'historico_interacoes' opportunity.cliente.id %}">Histórico <br>interação</a><br>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

opportunity/templates/sales_cycle_tracking/proposal.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Proposta</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <header class="shortcut-bar">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <nav>
            <a href="{% url 'registro'%}">Registro cliente</a>
            <a href="{% url 'opportunity_management'%}">Gerenciar vendas</a>
            <a href="{% url 'visualizar_clientes'%}">Visualizar cliente</a>
            <a href="{% url 'listar_propostas'%}">Ver propostas</a>
            <button class="btn-back" onclick="history.back()">Voltar</button>
        </nav>
    </header>
    
    <main class="main-content">
        <div class="form-container">
            <img src="{% static 'images/logo.png' %}" alt="Logo">
            <h2>Criar proposta</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group">
                        <label for="id_titulo">Título</label>
                        {{ form.titulo }}
                    </div>
                    <div class="form-group">
                        <label for="id_descricao">Descrição</label>
                        {{ form.descricao }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="id_preco">Preço</label>
                        {{ form.preco }}
                    </div>
                    <div class="form-group">
                        <label for="id_prazo">Prazo de validade</label>
                        {{ form.prazo_validade }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="id_itens">Itens</label>
                        {{ form.itens }}
                    </div>
                    <div class="form-group">
                        <label for="id_termos">Termos de condições</label>
                        {{ form.termos_condicoes }}
                    </div>
                </div>
                <button type="submit" class="btn-submit">Cadastrar</button>
            </form>
        </div>
    </main>

</body>
</html>