accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('registro/', views.registrar, name='registro'),
    path('visualizar/', views.visualizar_clientes, name='visualizar_clientes'),
    path('pesquisar/', views.pesquisar_clientes, name='pesquisar_clientes'),
    path('editar_cliente/<int:pk>/', views.editar_cliente, name='editar_cliente'),
    path('adicionar_interacao/<int:cliente_id>/', views.adicionar_interacao, name='adicionar_interacao'),
    path('historico_interacoes/<int:cliente_id>/', views.historico_interacoes, name='historico_interacoes'),
    path('perfil/<int:cliente_id>/', views.visualizar_perfil, name='visualizar_perfil'),
    path('compras_e_preferencias/<int:cliente_id>/', views.lista_compras_e_preferencias, name='lista_compras_e_preferencias'),
    path('adicionar_compra/<int:cliente_id>/', views.adicionar_compra, name='adicionar_compra'),
    path('adicionar_preferencia/<int:cliente_id>/', views.adicionar_preferencia, name='adicionar_preferencia'),
]

jacto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('opportunity/', include('opportunity.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class UserProfile(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField()
    telefone = models.CharField(max_length=20)
    data_nascimento = models.DateField()
    cpf_cnpj = models.CharField(max_length=20)
    numero = models.CharField(max_length=10)
    cidade = models.CharField(max_length=100)
    cep = models.CharField(max_length=9)
    rua = models.CharField(max_length=255)
    
    def __str__(self):
        return self.nome

class Interaction(models.Model):
    OP_CHOICES = (
        ('Reunião', 'Reunião'),
        ('Email', 'Email'),
        ('Chamada', 'Chamada'),
        ('Chat', 'Chat'),
    )
    id_cliente = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    data = models.DateField(default=timezone.now)
    choice = models.CharField(max_length=10, choices=OP_CHOICES)
    descricao = models.CharField(max_length=200)

    def __str__(self):
        return f"Interacao {self.id} - Cliente: {self.id_cliente}, Tipo: {self.choice}, Data: {self.data}"

class Compra(models.Model):
    id_cliente = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    data = models.DateField(default=timezone.now)  # Define a data automaticamente
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    produtos = models.CharField(max_length=200)

    def __str__(self):
        return f"Compra {self.id} - Cliente: {self.id_cliente}, Data: {self.data}"
    

class Preferencia(models.Model):
    id_cliente = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    preferencia = models.CharField(max_length=200)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nome', 'email', 'telefone', 'data_nascimento', 'cpf_cnpj', 'numero', 'cidade', 'cep', 'rua']
        
class ClienteSearchForm(forms.Form):
    nome = forms.CharField(label='Nome', required=False)
    cpf_cnpj = forms.CharField(label='CPF/CNPJ', required=False)

class InteractionForm(forms.ModelForm):
    class Meta:
        model = Interaction
        fields = ['choice', 'descricao']

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['valor', 'produtos']

class PreferenciaForm(forms.ModelForm):
    class Meta:
        model = Preferencia
        fields = ['preferencia']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from .models import *

def registrar(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('visualizar_clientes')
    else:
        form = UserProfileForm()
    return render(request, 'accounts/registro.html', {'form': form})



def visualizar_clientes(request):
    # Recupera todos os perfis de usuário
    perfis = UserProfile.objects.all()
    return render(request, 'clientes/visualizar_clientes.html', {'perfis': perfis})

def visualizar_perfil(request, cliente_id):
    cliente = get_object_or_404(UserProfile, pk=cliente_id)
    return render(request, 'clientes/visualizar_perfil.html', {'cliente': cliente})

def pesquisar_clientes(request):
    if request.method == 'POST':
        form = ClienteSearchForm(request.POST)
        if form.is_valid():
            nome = form.cleaned_data['nome']
            cpf_cnpj = form.cleaned_data['cpf_cnpj']
            clientes = UserProfile.objects.filter(nome__icontains=nome, cpf_cnpj__icontains=cpf_cnpj)
            return render(request, 'clientes/resultado_pesquisa.html', {'clientes': clientes})
    else:
        form = ClienteSearchForm()
    return render(request, 'clientes/pesquisar_clientes.html', {'form': form})

def editar_cliente(request, pk):
    cliente = get_object_or_404(UserProfile, pk=pk)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('visualizar_clientes')
    else:
        form = UserProfileForm(instance=cliente)
    return render(request, 'clientes/editar_cliente.html', {'form': form})

def historico_interacoes(request, cliente_id):
    cliente = UserProfile.objects.get(pk=cliente_id)
    interacoes = Interaction.objects.filter(id_cliente=cliente)
    return render(request, 'clientes/historico_interacoes.html', {'cliente': cliente, 'interacoes': interacoes})

def adicionar_interacao(request, cliente_id):
    cliente = UserProfile.objects.get(pk=cliente_id)
    if request.method == 'POST':
        form = InteractionForm(request.POST)
        if form.is_valid():
            interacao = form.save(commit=False)
            interacao.id_cliente = cliente
            interacao.save()
            return redirect('historico_interacoes', cliente_id=cliente.id)
    else:
        form = InteractionForm()
    return render(request, 'clientes/adicionar_interacao.html', {'form': form, 'cliente': cliente})

def lista_compras_e_preferencias(request, cliente_id):
    cliente = UserProfile.objects.get(pk=cliente_id)
    compras = cliente.compra_set.all()
    preferencias = cliente.preferencia_set.all()
    return render(request, 'compras/compras_preferencias.html', {'cliente': cliente, 'compras': compras, 'preferencias': preferencias})

def adicionar_compra(request, cliente_id):
    cliente = UserProfile.objects.get(pk=cliente_id)
    if request.method == 'POST':
        form = CompraForm(request.POST)
        if form.is_valid():
            compra = form.save(commit=False)
            compra.id_cliente = cliente
            compra.save()
            return redirect('lista_compras_e_preferencias', cliente_id=cliente.id)
    else:
        form = CompraForm()
    return render(request, 'compras/adicionar_compra.html', {'form': form})



def adicionar_preferencia(request, cliente_id):
    cliente = UserProfile.objects.get(pk=cliente_id)
    if request.method == 'POST':
        form = PreferenciaForm(request.POST)
        if form.is_valid():
            preferencia = form.save(commit=False)
            preferencia.id_cliente = cliente
            preferencia.save()
            return redirect('lista_compras_e_preferencias', cliente_id=cliente.id)
    else:
        form = PreferenciaForm()
    return render(request, 'compras/adicionar_preferencia.html', {'form': form})

accounts/templates/clientes/adicionar_interacao.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Interação</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="form-container">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <img src="{% static 'images/jacto.png' %}" alt="Jacto" class="jacto-logo">
        <h1>Adicionar interação</h1>
        <h2>{{ cliente.nome }}</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group">
                    <label for="id_nome">Tipo:</label>
                    {{ form.choice }}
                </div>
                <div class="form-group">
                    <label for="id_cpf_cnpj">Descrição:</label>
                    {{ form.descricao }}
                </div>
            </div>
            <button type="submit" class="btn-submit">Adicionar</button>
        </form>
    </div>
</body>
</html>

accounts/templates/clientes/editar_cliente.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Cliente</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="shortcut-bar">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <nav>
            <a href="{% url 'opportunity_management'%}">Gerenciar vendas</a>
            <a href="{% url 'pesquisar_clientes'%}">Pesquisar cliente</a>
            <a href="{% url 'visualizar_clientes'%}">Visualizar cliente</a>
            <a href="{% url 'criar_proposta'%}">Criar propostas</a>
            <button class="btn-back" onclick="history.back()">Voltar</button>
        </nav>
    </header>
    <main class="main-content">
        <div class="form-container">
            <img src="{% static 'images/logo.png' %}" alt="Logo">
            <h2>Editar cliente</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group">
                        <label for="id_nome">Nome</label>
                        {{ form.nome }}
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="id_telefone">Telefone</label>
                        {{ form.telefone }}
                    </div>
                    <div class="form-group">
                        <label for="id_cpf_cnpj">CPF/CNPJ</label>
                        {{ form.cpf_cnpj }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="id_data_nascimento">Data de nascimento</label>
                        {{ form.data_nascimento }}
                    </div>
                </div>
                <h2>Endereço</h2>
                <div class="form-row">
                    <div class="form-group">
                        <label for="id_rua">Rua</label>
                        {{ form.rua }}
                    </div>
                    <div class="form-group">
                        <label for="id_numero">Número</label>
                        {{ form.numero }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="id_cidade">Cidade</label>
                        {{ form.cidade }}
                    </div>
                    <div class="form-group">
                        <label for="id_cep">CEP</label>
                        {{ form.cep }}
                    </div>
                </div>
                <button type="submit" class="btn-submit">salvar alterações</button>
            </form>
        </div>
    </main>
</body>
</html>

accounts/templates/clientes/historico_interacoes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Histórico de Interação</title>
    <link rel="stylesheet" href="{% static 'css/style3.css' %}"> 
</head>
<body>
    <div class="container">
        {% load static %}
        <div class="header">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
            <img src="{% static 'images/jacto.png' %}" alt="Jacto" class="jacto-logo">
            <h1>Histórico de Interação</h1>
            <h2>{{ cliente.nome }}</h2>
        </div>
        <div class="interacoes">
            {% for interacao in interacoes %}
            <div class="interacao">
                <h3>Tipo: {{ interacao.choice }}</h3>
                <p>Descrição: {{ interacao.descricao }}</p>
                <p>Data: {{ interacao.data }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

accounts/templates/clientes/pesquisar_clientes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pesquisar Cliente</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="shortcut-bar">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <nav>
            <a href="{% url 'registro'%}">Registro cliente</a>
            <a href="{% url 'opportunity_management'%}">Gerenciar vendas</a>
            <a href="{% url 'visualizar_clientes'%}">Visualizar cliente</a>
            <a href="{% url 'criar_proposta'%}">Criar propostas</a>
            <button class="btn-back" onclick="history.back()">Voltar</button>
        </nav>
    </header>
    <main class="main-content">
        <div class="form-container">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
            <img src="{% static 'images/jacto.png' %}" alt="Jacto" class="jacto-logo">
            <h2>Pesquisar cliente</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group">
                        <label for="id_nome">Nome</label>
                        {{ form.nome }}
                    </div>
                    <div class="form-group">
                        <label for="id_cpf_cnpj">CPF/CNPJ</label>
                        {{ form.cpf_cnpj }}
                    </div>
                </div>
                <button type="submit" class="btn-submit">Pesquisar</button>
            </form>
        </div>
    </main>
</body>
</html>

accounts/templates/clientes/resultado_pesquisa.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultado da Pesquisa</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="shortcut-bar">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <nav>
            <button class="btn-back" onclick="history.back()">Voltar</button>
            <a href="{% url 'registro'%}">Registro cliente</a>
            <a href="{% url 'opportunity_management'%}">Gerenciar vendas</a>
            <a href="{% url 'pesquisar_clientes'%}">Pesquisar cliente</a>
            <a href="{% url 'criar_proposta'%}">Criar propostas</a>
            <button class="btn-back" onclick="history.back()">Voltar</button>
        </nav>
    </header>
    <main class="main-content">
        <div class="form-container">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
            <h2>Resultado pesquisa</h2>
            <div class="result-container">
                {% for cliente in clientes %}
                <div class="result-card">
                    <p><strong>Nome cliente</strong><br>{{ cliente.nome }}</p>
                    <p><strong>CPF/CNPJ</strong><br>{{ cliente.cpf_cnpj }}</p>
                    <a href="{% url 'visualizar_perfil' cliente.id %}" class="btn-view">visualizar perfil</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </main>
</body>
</html>

accounts/templates/clientes/visualizar_clientes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualizar Clientes</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="shortcut-bar">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <nav>
            <a href="{% url 'registro'%}">Registro cliente</a>
            <a href="{% url 'opportunity_management'%}">Gerenciar vendas</a>
            <a href="{% url 'pesquisar_clientes'%}">Pesquisar cliente</a>
            <a href="{% url 'criar_proposta'%}">Criar propostas</a>
            <button class="btn-back" onclick="history.back()">Voltar</button>
        </nav>
    </header>
    <main class="main-content">
        <div class="form-container">

            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
            <h2>Visualizar clientes</h2>
            <div class="result-container">
                {% for cliente in perfis %}
                <div class="result-card">
                    <p><strong>Nome cliente</strong><br>{{ cliente.nome }}</p>
                    <p><strong>CPF/CNPJ</strong><br>{{ cliente.cpf_cnpj }}</p>
                    <a href="{% url 'visualizar_perfil' cliente.id %}" class="btn-view">visualizar perfil</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </main>
</body>
</html>

accounts/templates/clientes/visualizar_perfil.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfil cliente</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="shortcut-bar">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        <nav>
            <a href="{% url 'registro'%}">Registro cliente</a>
            <a href="{% url 'opportunity_management'%}">Gerenciar vendas</a>
            <a href="{% url 'visualizar_clientes'%}">Visualizar cliente</a>
            <a href="{% url 'criar_proposta'%}">Criar propostas</a>
            <button class="btn-back" onclick="history.back()">Voltar</button>
        </nav>
    </header>
    <main class="main-content">
        <div class="form-container">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
            <h2>{{ cliente.nome }}</h2>
            <div class="result-container2">
                <p><strong>Email:</strong>{{ cliente.email }}</p>
                <p><strong>Telefone:</strong>{{ cliente.telefone }}</p>
                <p><strong>CPF/CNPJ:</strong>{{ cliente.cpf_cnpj }}</p>
                <p><strong>Data de Nascimento:</strong>{{ cliente.data_nascimento }}</p>
                <p><strong>Cidade:</strong>{{ cliente.cidade }}</p>
                <p><strong>CEP:</strong>{{ cliente.cep }}</p>
                <p><strong>Rua:</strong>{{ cliente.rua }}</p>
                <p><strong>Número:</strong>{{ cliente.numero }}</p>
            </div>
            <div class="result-container3">
                <a href="{% url 'editar_cliente' cliente.id %}" class="btn-view">Editar perfil</a>
                <a href="{% url 'adicionar_interacao' cliente.id %}" class="btn-view">Adicionar interação</a>
                <a href="{% url 'historico_interacoes' cliente.id %}" class="btn-view">Histórico interação</a>
                <a href="{% url 'adicionar_compra' cliente.id %}" class="btn-view">Adicionar compra</a>
                <a href="{% url 'adicionar_preferencia' cliente.id %}" class="btn-view">Adicionar preferência</a>
                <a href="{% url 'lista_compras_e_preferencias' cliente.id %}" class="btn-view">Compras e preferencias</a>
            </div>
        </div>
    </main>
</body>
</html>